### PR TITLE
[WIP] Remove Foundation dependencies where possible

### PR DESCRIPTION
**Pull request by Danappelxx**
Obviously, NSData is going to be difficult. I just got this ship started by removing the unnecessary imports and NSStrings.

### CODE REVIEW

**Comment by perezpaya** [comment]
Seems legit, I'll test and merge it later. Thanks for it man

**Comment by perezpaya** [comment]
Btw, @izqui we could write some tests, so we can integrate them with pull requests. With that we could have a better flow. Let's see if I've can spend some time refactoring a bit some parts and writing some tests.

**Comment by Danappelxx** [comment]
Fixed https://github.com/izqui/Taylor/issues/15

**Comment by izqui** [comment]
I tested it and it works okey. 

I agree with @alexperezpaya, we need tests.

**Pull request merged**
